---
- hosts: localhost
  become: yes
  vars:
    app: dr
    work_dir: /opt/dr
    rest_dir: dr-rest-service
    git_repo: spring-api
    back_dir: /tmp
    new_dirs: [ cache, bin, tmp, logs ]
    rm_dirs: [ '.git', install, LICENSE, 'README.md' ]
    port: 8090

  tasks:
    - name: stat foo
      stat: path="{{work_dir}}"
      register: wdir

    - name: backup spring api to backup directory
      archive:
        path: "{{work_dir}}"
        dest: "{{back_dir}}/{{item}}.tgz"
      with_items:
        - "{{app}}"
      when: wdir.stat.exists

    - name: remove work directory for a new working place
      file: path={{work_dir}} state=absent

    - name: create working place
      file: path={{work_dir}} state=directory mode=0755

    - name: clone docker jenkins source from git if os is centos
      git:
        repo: 'https://github.com/joechiu/spring-api.git'
        dest: '{{work_dir}}'

    - name: create directories for spring api to backup directory
      file: 
        path: "{{work_dir}}/{{item}}"
        state: directory
        mode: 0777
      with_items:
        - "{{new_dirs}}"

    - name: remove work directory to create a new workin place
      file: path={{work_dir}}/{{rest_dir}}/gradlew mode=0755

    - name: compile restful application by gradle
      command: chdir={{work_dir}}/{{rest_dir}} ./gradlew build --warning-mode=all

    - name: build the rest service source
      copy:
        src: "{{work_dir}}/{{rest_dir}}/build/libs/dr-rest-service-0.0.1-SNAPSHOT.jar"
        dest: "{{work_dir}}/bin/dr-rest-service.jar"

    - name: create restful daemon
      copy:
        src: "{{work_dir}}/install/bootrestfuld"
        dest: "/etc/init.d/bootrestfuld"

    - name: change mode to 0755
      file: 
        path: "{{item}}"
        mode: 0755
        owner: root 
        group: root
      with_items:
#         - "{{work_dir}}/bin"
        - "{{work_dir}}/bin/dr-rest-service.jar"
        - "/etc/init.d/bootrestfuld"

    - name: get boot restfuld | iptables rules
      shell: iptables -L
      register: iptablesrules
      always_run: yes

    - name: add boot restfuld iptables rule
      command: /sbin/iptables -I INPUT 1 -p tcp --dport {{port}} -j ACCEPT -m comment --comment "boot rest daemon"
      when: iptablesrules.stdout.find("boot rest") == -1

    - name: save iptables
      command: iptables-save

    - name: restart iptables
      service: name=ufw state=restarted

    - name: restart rest daemon
      shell: |
        /etc/init.d/bootrestfuld stop
        /etc/init.d/bootrestfuld start
      args:
        warn: no

#    this does well too
#    - name: start rest daemon
#      command: /etc/init.d/bootrestfuld start

    - name: cleaning redundant directories checkout from github
      file: 
        path: "{{work_dir}}/{{item}}"
        state: absent
      with_items:
        - "{{rest_dir}}" 
        - "{{rm_dirs}}" 
